#!/usr/bin/env bash

# if [ "$branch" = "master" ]; then
#   echo "You can't commit directly to master branch"
#   exit 1
# fi

find-program clang-format
find-program perl

commands=(encoding.pl format.sh)
for subcommand in ${commands[@]}; do
    "$GIT_COMMON_DIR/hooks/check/$subcommand"
    status=$?
    if [ $status -ne 0 ]; then
        exit $status
    fi
done
