#!/usr/bin/env bash
export HOOK_NAME=pre-push
source $(git rev-parse --git-common-dir)/hooks/common.sh
push_command=$(ps -ocommand= -p $PPID)

export REMOTE_REF=$1
if [[ "$push_command" =~ ":" ]]; then
  REMOTE_BRANCH=${push_command##*:}
  export REMOTE_BRANCH=${REMOTE_BRANCH%% *}
else
  export REMOTE_BRANCH=$CURRENT_BRANCH
fi

if [[ $REMOTE_BRANCH =~ $PROTECTED_BRANCH ]]; then
    echo >&2 "Never push code directly to the protected branch ($REMOTE_BRANCH)!"
    exit 1
fi

if [[ $push_command =~ $FORCE_PUSH_CMD ]]; then
    echo "Think before you type."
    $(prompt-to-confirm)
    status=$?
    if [ $status -ne 0 ]; then
        echo "Abort..."
        exit $status
    fi
fi

find-program git-lfs
git lfs pre-push "$@"
